//Used in case of change of field names in the database

module.exports = {
                    "orderNumber": "orderNumber",
                    "orderSource": "orderSource",
                    "customerId": "customerId",
                    "customerName": "customerName",
                    "receiverName": "receiverName",
                    "address": "address",
                    "district": "district",
                    "city": "city",
                    "province": "province",
                    "zipcode": "zipcode",
                    "phone": "phone",
                    "paymentMethod": "paymentMethod",
                    "outTradeNo": "outTradeNo",
                    "deliveryCost": "deliveryCost",
                    "totalDiscount": "totalDiscount",
                    "totalAmount": "totalAmount",
                    "payment": "payment",
                    "lastmile": "lastmile",
                    "ecommerceCreateTime": "ecommerceCreateTime",
                    "ecommercePaymentTime": "ecommercePaymentTime",
                    "ecommerceEndTime": "ecommerceEndTime",
                  };